// /**
//  * This code was generated by v0 by Vercel.
//  * @see https://v0.dev/t/Lj4TnTET7MG
//  * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
//  */
// export function Feature() {
//   return (
//     <section className="w-full py-12 md:py-24">
//       <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
//         <div className="space-y-3">
//           <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
//             Features
//           </h2>
//           <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
//             The most useful tools for your workflow. Get started in seconds.
//           </p>
//         </div>
//         <div className="grid w-full grid-cols-1 items-center justify-center gap-6 md:grid-cols-3 lg:gap-12">
//           <div className="flex flex-col items-center justify-center space-y-2">
//             <TerminalIcon className="w-12 h-12" />
//             <h3 className="text-lg font-semibold">Command Line</h3>
//             <p className="text-sm text-gray-500 dark:text-gray-400">
//               Powerful command-line interface available directly in your
//               browser.
//             </p>
//           </div>
//           <div className="flex flex-col items-center justify-center space-y-2">
//             <CodeIcon className="w-12 h-12" />
//             <h3 className="text-lg font-semibold">Code Review</h3>
//             <p className="text-sm text-gray-500 dark:text-gray-400">
//               Built-in collaboration tools to manage your code review process.
//             </p>
//           </div>
//           <div className="flex flex-col items-center justify-center space-y-2">
//             <ComponentIcon className="w-12 h-12" />
//             <h3 className="text-lg font-semibold">Design System</h3>
//             <p className="text-sm text-gray-500 dark:text-gray-400">
//               Create, document, and manage your design system with components.
//             </p>
//           </div>
//           <div className="flex flex-col items-center justify-center space-y-2">
//             <KeyIcon className="w-12 h-12" />
//             <h3 className="text-lg font-semibold">API</h3>
//             <p className="text-sm text-gray-500 dark:text-gray-400">
//               Securely deploy your API and functions with serverless
//               infrastructure.
//             </p>
//           </div>
//           <div className="flex flex-col items-center justify-center space-y-2">
//             <DatabaseIcon className="w-12 h-12" />
//             <h3 className="text-lg font-semibold">Database</h3>
//             <p className="text-sm text-gray-500 dark:text-gray-400">
//               Managed databases for your web projects. Focus on your data, not
//               your database.
//             </p>
//           </div>
//           <div className="flex flex-col items-center justify-center space-y-2">
//             <ImageIcon className="w-12 h-12" />
//             <h3 className="text-lg font-semibold">Image Optimization</h3>
//             <p className="text-sm text-gray-500 dark:text-gray-400">
//               Automatically optimize images using the latest techniques.
//             </p>
//           </div>
//         </div>
//       </div>
//     </section>
//   );
// }

// function CodeIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <polyline points="16 18 22 12 16 6" />
//       <polyline points="8 6 2 12 8 18" />
//     </svg>
//   );
// }

// function ComponentIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M5.5 8.5 9 12l-3.5 3.5L2 12l3.5-3.5Z" />
//       <path d="m12 2 3.5 3.5L12 9 8.5 5.5 12 2Z" />
//       <path d="M18.5 8.5 22 12l-3.5 3.5L15 12l3.5-3.5Z" />
//       <path d="m12 15 3.5 3.5L12 22l-3.5-3.5L12 15Z" />
//     </svg>
//   );
// }

// function DatabaseIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <ellipse cx="12" cy="5" rx="9" ry="3" />
//       <path d="M3 5V19A9 3 0 0 0 21 19V5" />
//       <path d="M3 12A9 3 0 0 0 21 12" />
//     </svg>
//   );
// }

// function ImageIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
//       <circle cx="9" cy="9" r="2" />
//       <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
//     </svg>
//   );
// }

// function KeyIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <circle cx="7.5" cy="15.5" r="5.5" />
//       <path d="m21 2-9.6 9.6" />
//       <path d="m15.5 7.5 3 3L22 7l-3-3" />
//     </svg>
//   );
// }

// function TerminalIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <polyline points="4 17 10 11 4 5" />
//       <line x1="12" x2="20" y1="19" y2="19" />
//     </svg>
//   );
// }
// export default Feature;
